### PR TITLE
Add config and custom template support

### PR DESCRIPTION
**Pull request by ncoden**
Implement one proposal from https://github.com/sachinchoolur/angular-flash/issues/34

**Allow to**:
- Configure plugin in Angular config phase, instead of in the HTML
- Use a custom flash message template, given in config or transcluded

**Other changes**:
- Add default configuration
- Write HTML on several lines

**Example**:
```Javascript
app.config((FlashProvider) => {
    Flashprovider.setTimeout(3000); // default: 5000

    FlashProvider.setTemplatePreset('transclude'); // default: 'bootstrap'
    // Or:
    Flash provider.setTemplate('{{ flash.text }}');
});
```
```HTML
<flash-message>
    <div class="my-flash-message">
        {{ flash.text }}
    </div>
</flash-message>
```

### CODE REVIEW

**Comment by RoopeHakulinen** [comment]
Thanks for the PR. I'll hope to get it checked during the weekend!

**Comment by ncoden** [comment]
Hi. I finally found some bugs I don't know how to fix: How to pass datas from a directive to the scope (or wathever) of its transcluded content. I didn't now that the transcluded content inherit the scope of the directive parent.

**Comment by ncoden** [comment]
I fixed this. I didn't found any doc / questions and solutions on forums about this problem, so it's a little dirty. But it do the job :)

**Comment by RoopeHakulinen** [comment]
Hey, I took a look and it seems to work okay with the current usage also which is great! Now, to publish this we would need a compiled version and documentation. 

To compile a new dist files and run tests against them, run 
```
npm install
npm install -g grunt
grunt
./node_modules/karma/bin/karma start
```

Documentation can be found from `README.md` and `demo/index.html`, these would need to be updated accordingly. 

If you could take care of those parts, I'd be happy to draft a new release (v2.3.0) for this.

**Comment by ncoden** [comment]
Ok, I thought you would do this in an other "Release x.x.x" commit.

**Comment by ncoden** [comment]
poke @RoopeHakulinen 
`2.3.0` ready. I included the commit you just made ;)

**Comment by RoopeHakulinen** [comment]
Great, seems to work on demo, tests pass and README is updated. I'll add the documentation changes to the demo too and draft a release soon.

**Comment by ncoden** [comment]
I've already changed the version number. You only have too publish on npm & bower :)

**Comment by RoopeHakulinen** [comment]
Yeah, I noticed and those are done already. Thanks again :)

**Comment by ncoden** [comment]
No problem. I only need these features.
Thank you for added me to contributors.

**Pull request merged**
